# Generated by Django 4.2.30 on 2026-09-02 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0002_alter_productos_precio_alter_productos_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero_telfeono',
            field=models.IntegerField(),
        ),
    ]
