# Generated by Django 4.2.30 on 2026-09-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0003_alter_productos_descripcion_alter_productos_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
