# Generated by Django 4.2.30 on 2026-09-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0004_productos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
