# Generated by Django 4.2.30 on 2026-09-05 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0005_productos_marca_alter_productos_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='cantidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='productos',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
