# Generated by Django 4.2.30 on 2026-09-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0006_productos_cantidad_productos_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='cantidad',
        ),
    ]
