# Generated by Django 4.2.30 on 2026-09-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0007_remove_productos_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
