# Generated by Django 4.2.30 on 2026-09-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0009_perfiles_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
    ]
