# Generated by Django 4.2.30 on 2026-09-23 01:37

import Almacen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0010_productos_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='productos',
            name='lote',
            field=models.CharField(default='Sin lote', max_length=100),
        ),
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(max_length=100, validators=[Almacen.models.validar_categoria]),
        ),
        migrations.AlterField(
            model_name='productos',
            name='marca',
            field=models.CharField(default='Sin marca', max_length=100),
        ),
    ]
