# Generated by Django 4.2.30 on 2026-09-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0011_remove_productos_descripcion_productos_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
