# Generated by Django 4.2.30 on 2026-09-28 23:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0012_alter_productos_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_ventas', models.IntegerField(db_column='ID_ventas', primary_key=True, serialize=False)),
                ('id_caja', models.IntegerField(db_column='ID_Caja')),
                ('total', models.DecimalField(decimal_places=2, max_digits=65)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(db_column='Hora')),
                ('id_clientes', models.IntegerField(db_column='ID_Clientes')),
                ('estado_de_pago', models.CharField(db_column='Estado_de_pago', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetallesVentas',
            fields=[
                ('id_detalles_ventas', models.IntegerField(db_column='ID_Detalles_Ventas', primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(db_column='Cantidad', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario_compra', models.DecimalField(db_column='Precio_Unitario_Compra', decimal_places=2, max_digits=65)),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, max_digits=65)),
                ('producto', models.ForeignKey(db_column='ID_Productos', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ventas', to='Almacen.productos')),
                ('venta', models.ForeignKey(db_column='ID_ventas', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Almacen.ventas')),
            ],
        ),
    ]
