# Generated by Django 4.2.30 on 2026-10-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0013_ventas_detallesventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesventas',
            name='cantidad',
            field=models.IntegerField(db_column='Cantidad'),
        ),
    ]
