# Generated by Django 4.2.30 on 2026-10-04 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0014_alter_detallesventas_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='stock',
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
