# Generated by Django 4.2.30 on 2026-10-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0015_remove_productos_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='numero_telfeono',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numero_telefono',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
