# Generated by Django 4.2.30 on 2026-10-04 22:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0016_remove_proveedor_numero_telfeono_proveedor_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(default='Confirmado', max_length=20)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Almacen.proveedor')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LotesProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('stock_actual', models.IntegerField(default=0)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='Almacen.productos')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Almacen.compras')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Almacen.productos')),
            ],
        ),
    ]
