# Generated by Django 4.2.30 on 2026-10-04 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0017_compras_lotesproducto_detallescompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Almacen.proveedor'),
        ),
    ]
