# Generated by Django 4.2.30 on 2026-10-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0018_alter_compras_id_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='id_ventas',
            field=models.AutoField(db_column='ID_ventas', primary_key=True, serialize=False),
        ),
    ]
