# Generated by Django 4.2.30 on 2026-10-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0019_alter_ventas_id_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_clientes', models.AutoField(db_column='ID_Clientes', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
