# Generated by Django 4.2.30 on 2026-10-06 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0020_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(db_column='ID_Caja', primary_key=True, serialize=False)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_final_esperado', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('monto_final_real', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
