# Generated by Django 4.2.30 on 2026-10-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0021_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='estado_de_pago',
            field=models.CharField(db_column='Estado_de_pago', max_length=20),
        ),
    ]
